// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

import (
	"time"
)

// Defines values for OrderStatus.
const (
	ACCEPTED   OrderStatus = "ACCEPTED"
	CANCELLED  OrderStatus = "CANCELLED"
	COMPLETED  OrderStatus = "COMPLETED"
	COOKING    OrderStatus = "COOKING"
	CREATED    OrderStatus = "CREATED"
	DELIVERING OrderStatus = "DELIVERING"
	READY      OrderStatus = "READY"
)

// Category defines model for Category.
type Category struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// CreateOrderItem defines model for CreateOrderItem.
type CreateOrderItem struct {
	MenuItemId string `json:"menuItemId"`
	Quantity   int    `json:"quantity"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	CustomerRef string            `json:"customerRef"`
	Items       []CreateOrderItem `json:"items"`
	VenueId     string            `json:"venueId"`
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// ItemsUnavailableError defines model for ItemsUnavailableError.
type ItemsUnavailableError struct {
	Details *[]struct {
		MenuItemId *string `json:"menuItemId,omitempty"`
		Reason     *string `json:"reason,omitempty"`
	} `json:"details,omitempty"`
	Error *string `json:"error,omitempty"`
}

// MenuItem defines model for MenuItem.
type MenuItem struct {
	CategoryId   *string `json:"categoryId,omitempty"`
	Currency     *string `json:"currency,omitempty"`
	Description  *string `json:"description,omitempty"`
	Id           *string `json:"id,omitempty"`
	IsAvailable  *bool   `json:"isAvailable,omitempty"`
	Name         *string `json:"name,omitempty"`
	PriceKopecks *int64  `json:"priceKopecks,omitempty"`
}

// Order defines model for Order.
type Order struct {
	CreatedAt    *time.Time   `json:"createdAt,omitempty"`
	Currency     *string      `json:"currency,omitempty"`
	CustomerRef  *string      `json:"customerRef,omitempty"`
	Id           *string      `json:"id,omitempty"`
	Items        *[]OrderItem `json:"items,omitempty"`
	Status       *OrderStatus `json:"status,omitempty"`
	TotalKopecks *int64       `json:"totalKopecks,omitempty"`
	VenueId      *string      `json:"venueId,omitempty"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// OrderItem defines model for OrderItem.
type OrderItem struct {
	MenuItemId   *string `json:"menuItemId,omitempty"`
	Name         *string `json:"name,omitempty"`
	PriceKopecks *int64  `json:"priceKopecks,omitempty"`
	Quantity     *int    `json:"quantity,omitempty"`
}

// Venue defines model for Venue.
type Venue struct {
	City *string `json:"city,omitempty"`
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// VenueMenu defines model for VenueMenu.
type VenueMenu struct {
	Categories *[]Category `json:"categories,omitempty"`
	Items      *[]MenuItem `json:"items,omitempty"`
	Venue      *Venue      `json:"venue,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListVenuesParams defines parameters for ListVenues.
type ListVenuesParams struct {
	City *string `form:"city,omitempty" json:"city,omitempty"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest
